# Generated by Django 6.0.2 on 2026-02-12 12:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('trip_type', models.CharField(choices=[('one_way', 'One Way'), ('round_trip', 'Round Trip'), ('multi_day', 'Multi Day')], max_length=20)),
                ('pickup_location', models.TextField()),
                ('pickup_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('pickup_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('drop_location', models.TextField()),
                ('drop_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('drop_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('pickup_date', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('passenger_count', models.IntegerField()),
                ('purpose', models.CharField(blank=True, choices=[('wedding', 'Wedding'), ('religious', 'Religious Trip'), ('family_trip', 'Family Trip'), ('corporate', 'Corporate'), ('school_tour', 'School Tour'), ('other', 'Other')], max_length=50, null=True)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('estimated_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('estimated_route', models.TextField(blank=True, null=True)),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('driver_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('night_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('toll_estimate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=4)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('operator_payout', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled_by_customer', 'Cancelled by Customer'), ('cancelled_by_operator', 'Cancelled by Operator'), ('expired', 'Expired')], default='pending', max_length=30)),
                ('operator_response', models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=20, null=True)),
                ('operator_response_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('payment_mode', models.CharField(choices=[('online_full', 'Pay Full Online'), ('online_advance', 'Pay Advance Online'), ('pay_driver', 'Pay Driver (Cash)')], default='online_full', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('advance_paid', 'Advance Paid'), ('fully_paid', 'Fully Paid'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('advance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('operator_payout_status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('operator_payout_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled_by_customer', 'Cancelled by Customer'), ('cancelled_by_operator', 'Cancelled by Operator'), ('expired', 'Expired')], max_length=30)),
                ('new_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled_by_customer', 'Cancelled by Customer'), ('cancelled_by_operator', 'Cancelled by Operator'), ('expired', 'Expired')], max_length=30)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'booking_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('discount_type', models.CharField(choices=[('flat', 'Flat Amount'), ('percentage', 'Percentage')], max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_booking', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('usage_limit', models.IntegerField(blank=True, null=True)),
                ('used_count', models.IntegerField(default=0)),
                ('per_user_limit', models.IntegerField(default=1)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'coupons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discount_applied', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'coupon_usage',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cf_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('cf_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('cf_payment_session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('payment_type', models.CharField(choices=[('advance', 'Advance'), ('full', 'Full Payment'), ('remaining', 'Remaining Balance'), ('refund', 'Refund')], max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('upi', 'UPI'), ('card', 'Credit/Debit Card'), ('netbanking', 'Net Banking'), ('wallet', 'Wallet')], max_length=30, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('authorized', 'Authorized'), ('captured', 'Captured'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='created', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
