# Generated by Django 6.0.2 on 2026-02-13 14:00

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(
                condition=Q(status='created'),
                fields=('booking', 'payment_type'),
                name='uniq_pending_payment_per_booking_type',
            ),
        ),
    ]
