# Generated by Django 6.0.2 on 2026-02-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_payment_pending_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='driver_cash_received',
            field=models.BooleanField(default=False, help_text='Operator confirms cash received from customer'),
        ),
        migrations.AddField(
            model_name='booking',
            name='driver_cash_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Auto-expire pending booking after this time (created_at + 2 hours)', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount to be paid to driver in cash', max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('advance_paid', 'Advance Paid'), ('fully_paid', 'Fully Paid'), ('refund_pending', 'Refund Pending'), ('refund_failed', 'Refund Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='bookinghistory',
            name='old_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled_by_customer', 'Cancelled by Customer'), ('cancelled_by_operator', 'Cancelled by Operator'), ('expired', 'Expired')], default='', help_text='Empty on initial booking creation.', max_length=30),
        ),
    ]
