# Generated by Django 6.0.2 on 2026-02-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_driver_cash_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='idempotency_key',
            field=models.CharField(
                blank=True,
                help_text='Unique key to prevent duplicate payment processing',
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(
                choices=[
                    ('created', 'Created'),
                    ('authorized', 'Authorized'),
                    ('captured', 'Captured'),
                    ('failed', 'Failed'),
                    ('refund_pending', 'Refund Pending'),
                    ('refund_failed', 'Refund Failed'),
                    ('refunded', 'Refunded'),
                ],
                default='created',
                max_length=20,
            ),
        ),
    ]
