# Generated by Django 6.0.2 on 2026-02-12 12:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('bus_type', models.CharField(choices=[('mini_bus', 'Mini Bus (17 seater)'), ('medium_bus', 'Medium Bus (25-30 seater)'), ('luxury_coach', 'Luxury Coach (40+ seater)'), ('tempo_traveller', 'Tempo Traveller')], max_length=50)),
                ('seating_capacity', models.IntegerField()),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('make_model', models.CharField(blank=True, max_length=100, null=True)),
                ('manufacture_year', models.IntegerField(blank=True, null=True)),
                ('ac_type', models.CharField(choices=[('ac', 'AC'), ('non_ac', 'Non-AC'), ('both', 'AC & Non-AC')], max_length=20)),
                ('fuel_type', models.CharField(choices=[('diesel', 'Diesel'), ('cng', 'CNG'), ('electric', 'Electric')], default='diesel', max_length=20)),
                ('price_per_km', models.DecimalField(decimal_places=2, max_digits=8)),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('driver_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('night_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('base_city', models.CharField(default='Jaipur', max_length=100)),
                ('base_area', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rating_avg', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('rating_count', models.IntegerField(default=0)),
                ('total_trips', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'buses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusAmenity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amenity', models.CharField(choices=[('music_system', 'Music System'), ('pushback_seats', 'Pushback Seats'), ('charging_points', 'Charging Points'), ('first_aid', 'First Aid Kit'), ('fire_extinguisher', 'Fire Extinguisher'), ('reading_lights', 'Reading Lights'), ('luggage_space', 'Luggage Space'), ('water_bottles', 'Water Bottles'), ('dj_system', 'DJ System'), ('wifi', 'WiFi'), ('tv_screen', 'TV Screen'), ('gps_tracking', 'GPS Tracking'), ('cctv', 'CCTV'), ('blankets_pillows', 'Blankets & Pillows')], max_length=50)),
            ],
            options={
                'db_table': 'bus_amenities',
            },
        ),
        migrations.CreateModel(
            name='BusPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo_url', models.URLField()),
                ('photo_type', models.CharField(choices=[('exterior_front', 'Exterior Front'), ('exterior_side', 'Exterior Side'), ('interior', 'Interior'), ('seats', 'Seats'), ('dashboard', 'Dashboard'), ('other', 'Other')], max_length=30)),
                ('display_order', models.IntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bus_photos',
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilityBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blocked_date', models.DateField()),
                ('block_reason', models.CharField(choices=[('booked_platform', 'Booked (Platform)'), ('booked_external', 'Booked (External)'), ('maintenance', 'Maintenance'), ('personal', 'Personal')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, help_text='Set when blocked due to a platform booking.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_dates', to='bookings.booking')),
            ],
            options={
                'db_table': 'availability_blocks',
                'ordering': ['blocked_date'],
            },
        ),
    ]
