# Generated by Django 6.0.2 on 2026-02-12 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='operator',
            field=models.ForeignKey(limit_choices_to={'role': 'operator'}, on_delete=django.db.models.deletion.CASCADE, related_name='buses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='availabilityblock',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_blocks', to='buses.bus'),
        ),
        migrations.AddField(
            model_name='busamenity',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='buses.bus'),
        ),
        migrations.AddField(
            model_name='busphoto',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='buses.bus'),
        ),
        migrations.AddIndex(
            model_name='bus',
            index=models.Index(fields=['operator'], name='buses_operato_67d44f_idx'),
        ),
        migrations.AddIndex(
            model_name='bus',
            index=models.Index(fields=['base_city'], name='buses_base_ci_2a63e0_idx'),
        ),
        migrations.AddIndex(
            model_name='bus',
            index=models.Index(fields=['bus_type'], name='buses_bus_typ_468035_idx'),
        ),
        migrations.AddIndex(
            model_name='bus',
            index=models.Index(fields=['seating_capacity'], name='buses_seating_d1cabe_idx'),
        ),
        migrations.AddIndex(
            model_name='bus',
            index=models.Index(fields=['is_active', 'is_approved'], name='buses_is_acti_db4d4e_idx'),
        ),
        migrations.AddIndex(
            model_name='availabilityblock',
            index=models.Index(fields=['bus', 'blocked_date'], name='availabilit_bus_id_4834de_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='availabilityblock',
            unique_together={('bus', 'blocked_date')},
        ),
        migrations.AddIndex(
            model_name='busamenity',
            index=models.Index(fields=['bus'], name='bus_ameniti_bus_id_e4017a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='busamenity',
            unique_together={('bus', 'amenity')},
        ),
        migrations.AddIndex(
            model_name='busphoto',
            index=models.Index(fields=['bus'], name='bus_photos_bus_id_9735ab_idx'),
        ),
    ]
