# Generated by Django 6.0.2 on 2026-02-13 11:42

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bus',
            name='buses_is_acti_db4d4e_idx',
        ),
        migrations.AlterField(
            model_name='bus',
            name='rating_avg',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='bus',
            name='seating_capacity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddIndex(
            model_name='bus',
            index=models.Index(fields=['is_active', 'approval_status'], name='buses_is_acti_bd8449_idx'),
        ),
        migrations.AddConstraint(
            model_name='busphoto',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('bus',), name='unique_primary_photo_per_bus'),
        ),
        migrations.RemoveField(
            model_name='bus',
            name='is_approved',
        ),
    ]
