# Generated by Django 6.0.2 on 2026-02-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0003_remove_is_approved_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilityblock',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional notes for manual blocks (e.g., maintenance details)', null=True),
        ),
    ]
