# Generated by Django 6.0.2 on 2026-02-12 12:17

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('buses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in format: +919829012345', regex='^\\+?1?\\d{9,15}$')])),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('operator', 'Bus Operator'), ('admin', 'Admin')], default='customer', max_length=20)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('business_name', models.CharField(blank=True, max_length=200, null=True)),
                ('business_type', models.CharField(blank=True, choices=[('individual', 'Individual'), ('company', 'Company')], max_length=50, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=20, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=15, null=True)),
                ('bank_account', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_ifsc', models.CharField(blank=True, max_length=15, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('rating_avg', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('rating_count', models.IntegerField(default=0)),
                ('total_bookings', models.IntegerField(default=0)),
                ('subscription_tier', models.CharField(choices=[('free', 'Free'), ('pro', 'Professional'), ('enterprise', 'Enterprise')], default='free', max_length=20)),
                ('subscription_expires_at', models.DateTimeField(blank=True, null=True)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=4)),
                ('preferred_language', models.CharField(choices=[('hi', 'Hindi'), ('en', 'English')], default='hi', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('aadhar', 'Aadhaar Card'), ('pan', 'PAN Card'), ('bank_proof', 'Bank Proof'), ('rc', 'Registration Certificate'), ('fitness_certificate', 'Fitness Certificate'), ('permit', 'Bus Permit'), ('insurance', 'Insurance'), ('puc', 'PUC Certificate'), ('road_tax', 'Road Tax Receipt'), ('driver_license', 'Driver License'), ('driver_aadhar', 'Driver Aadhaar'), ('police_verification', 'Police Verification'), ('gst_certificate', 'GST Certificate'), ('trade_license', 'Trade License'), ('company_registration', 'Company Registration')], max_length=50)),
                ('document_url', models.URLField()),
                ('document_number', models.CharField(blank=True, max_length=50, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bus', models.ForeignKey(blank=True, help_text='NULL for owner-level docs; set for bus-specific docs.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='buses.bus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'operator_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('booking_confirmed', 'Booking Confirmed'), ('booking_cancelled', 'Booking Cancelled'), ('new_review', 'New Review'), ('payment_received', 'Payment Received'), ('document_verified', 'Document Verified'), ('document_rejected', 'Document Rejected'), ('operator_verified', 'Operator Verified'), ('payout_processed', 'Payout Processed')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['phone'], name='users_phone_af6883_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role'], name='users_role_0ace22_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['city'], name='users_city_9c6023_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_verified'], name='users_is_veri_63cd6e_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user'], name='operator_do_user_id_32e83f_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['bus'], name='operator_do_bus_id_3fede8_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['expiry_date'], name='operator_do_expiry__f63798_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='notificatio_user_id_a4dd5c_idx'),
        ),
    ]
