# Generated by Django 6.0.2 on 2026-02-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_supabase_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='total_buses',
            field=models.IntegerField(default=0),
        ),
    ]
