# Generated by Django 6.0.2 on 2026-02-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_total_buses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bank_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pan_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
