# Generated by Django 6.0.2 on 2026-02-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_expand_sensitive_fields_for_encryption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rating_avg',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('booking_confirmed', 'Booking Confirmed'), ('booking_cancelled', 'Booking Cancelled'), ('new_review', 'New Review'), ('payment_received', 'Payment Received'), ('document_verified', 'Document Verified'), ('document_rejected', 'Document Rejected'), ('operator_verified', 'Operator Verified'), ('operator_rejected', 'Operator Rejected'), ('payout_processed', 'Payout Processed')], max_length=50),
        ),
    ]
