# Generated by Django 6.0.2 on 2026-02-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_rating_avg_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='whatsapp_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='whatsapp_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('booking_created', 'Booking Created'), ('booking_confirmed', 'Booking Confirmed'), ('booking_rejected', 'Booking Rejected'), ('booking_cancelled', 'Booking Cancelled'), ('booking_expired', 'Booking Expired'), ('trip_reminder', 'Trip Reminder'), ('new_review', 'New Review'), ('payment_received', 'Payment Received'), ('document_verified', 'Document Verified'), ('document_rejected', 'Document Rejected'), ('operator_verified', 'Operator Verified'), ('operator_rejected', 'Operator Rejected'), ('payout_processed', 'Payout Processed')], max_length=50),
        ),
    ]
