# Generated by Django 6.0.2 on 2026-02-12 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='busreview',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='busreview',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operatorreview',
            name='operator',
            field=models.ForeignKey(limit_choices_to={'role': 'operator'}, on_delete=django.db.models.deletion.CASCADE, related_name='operator_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operatorreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_reviews_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='busreview',
            index=models.Index(fields=['bus'], name='reviews_bus_id_10bf30_idx'),
        ),
        migrations.AddIndex(
            model_name='busreview',
            index=models.Index(fields=['operator'], name='reviews_operato_4d682a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='operatorreview',
            unique_together={('operator', 'reviewer')},
        ),
    ]
